### ISSUE TITLE
Add foreign test vectors

### ISSUE THREAD

**Issue by cfcs** [mirage/decompress#36] opened 2017-10-28 00:14 UTC
Just so we know we agree with foreign implementations :)

Here are some:
- https://github.com/madler/zlib/blob/master/test/infcover.c
- https://github.com/imaya/zlib.js/tree/develop/test
- http://lkml.iu.edu/hypermail/linux/kernel/0808.3/2183.html

I wasn't able to find a set of official test vectors, but perhaps someone with stronger google-fu than me can be of assistance.

**Comment by dinosaure** [comment] 2017-10-28 04:13
If you look the [tests of decompress](https://github.com/mirage/decompress/blob/master/test/test.ml#L147), you can see a systematic comparison with `camlzip` which provides the officiel foreign implementation. Then, the tests cases are the binary in the `/bin/` directory (see output of [travis](https://travis-ci.org/mirage/decompress/builds/289704055)).

So, I can say, for all of these, we agree with foreign implementation.

When I look your links, the tests cases are something like what I do:
- `zlib.js` deflate and inflate an random input, my tests do not do that (boring to reproduce) but the AFL test do it.

About [self test for zlib crypto](http://lkml.iu.edu/hypermail/linux/kernel/0808.3/2183.html), `decompress` respects the [RFC 1951](https://www.ietf.org/rfc/rfc1951.txt) __but__ does not produce exactly the same output than `zlib` for 2 reasons:
- the deflate algorithm is not the same (it comes from [blosc](https://github.com/Blosc/c-blosc)) so we don't generate the same output - however, we should produce exactly the same huffman tree.
- the behavior about `Z_SYNC`, `Z_FULL` and `Z_PARTIAL` is not exactly the same. Firstly, because this behavior is not clear in the `zlib` standard (and change sometimes - for example `Z_PARTIAL` was deprecated for a long time but it used by the SSH protocol and this depreciation was removed but it stays relevant ...).

So, try to compare _byte per byte_ the output of `decompress` and the output of `zlib` is not relevant for me for these reasons.

However, [`zlib`](https://github.com/madler/zlib/blob/master/test/infcover.c) provides some useful fails cases which could be interesting to integrate (bad window, bad header, etc.).

About the behavior expected, I can _formalize_ what `decompress` does exactly about the flush method. However, I don't want to simulate, follow, and respect a behavior from an implementation, which, although stable, does not have a well-defined document (like a standard). This implementation ensure only to respect the [RFC 1951](https://www.ietf.org/rfc/rfc1951.txt) - and about the expected behavior of `Z_PARTIAL`, I can do something for SSH but it's wrong to rely on not formalized implementation.

**Comment by cfcs** [comment] 2017-10-28 17:19
I agree that randomized testing is mostly useful for self-integrity-checking, and not very useful to port.

> So, try to compare byte per byte the output of decompress and the output of zlib is not relevant for me for these reasons.

I think the most relevant is to test that we can *inflate* (decompress) to the same bytes as `zlib`.
Whether `zlib` accepts our *deflated* (compressed) output is a different thing, harder to test.

> However, zlib provides some useful fails cases which could be interesting to integrate (bad window, bad header, etc.).

Yeah, I guess we can steal the bits and pieces that make sense.
Test samples to do with corner cases sound useful to me.

Re: SSH: maybe @haesbaert has thoughts on this? do you want to use compression in `awa-ssh`?

**Comment by dinosaure** [comment] 2018-09-25 21:49
See #56

**Comment by dinosaure** [comment] 2018-09-25 21:57
I did not close this issue because I did not integrate all tests from `zlib` and need to separate tests which describe behavior of `zlib` on buffer (which can not be replicated on `decompress`) and tests about valid and invalid input/output.

**Comment by dinosaure** [comment] 2019-08-30 08:43
Close by #74 where all tests of `zlib` are now included into `decompress`.

**Closed by dinosaure** 2019-08-30 08:43 UTC
